### PR TITLE
Leaderboard: hit the API

### PR DESCRIPTION
**Pull request by chiztechnology**
In this pull request, we continued working on the Leaderboard list app, by implementing sending and receiving data from/to the Leaderboard API. 🎊 

### Project requirements

- Read the [Leaderboard API documentation](https://www.notion.so/microverse/Leaderboard-API-service-24c0c3c116974ac49488d4eb0267ade3) to learn how to use this API. 💯 
- Create a new game with the name of your choice by using the API. 💯 
- Make sure that you saved the ID of your game that will be returned by API. 💯 
- Implement the "Refresh" button that will get all scores for a game created by you from the API (receiving data from the API and parsing the JSON). 💯 
- Implement the form "Submit" button that will save a score for a game created by you (sending data to the API). 💯 
- Use arrow functions instead of the function keyword. 💯 
- Use async and await JavaScript features to consume the API. 💯 

Thank you for your review in order to keep improving our technical skills.
Best regards

### CODE REVIEW

**Review by Favourezeugwa — APPROVED** [review]
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @chiztechnology , 

I am Favour 👩🏽 , your reviewer for this PR.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

happy

## Highlights 💯 
- No Linter errors ✔️
- Used async and await with the fetch method ✔️
- The submit button hits the POST API endpoint ✔️
- Good usage of **arrow functions** ✔️
- App runs as expected ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by chiztechnology** [comment]
Thanks alot for the great and professionnal review dear @Favourezeugwa.
I really appreciate 🤝

**Comment by chiztechnology** [comment]
please find in this same pull request the last requirements about styling the project.

## Leaderboard: final touches

- At this point you should have a fully working app that uses only basic styles to make the layout work, according to the given Template ✅  💯 
- Now you should improve the look and feel of the application, adding the styles of your choice. ✅  💯 
- Please keep the general layout of the wireframe, this is the only mandatory requirement. ✅  💯 
- You can use plain CSS or any CSS framework, it's up to you. ✅  💯 


Best regards

**Review by cynthiainga — APPROVED** [review]
## STATUS APPROVED 🏆 🍹 ✔️ 

Hi @chiztechnology, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] App runs as expected ✔️


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
